### PR TITLE
#46 test & release windows binary

### PR DESCRIPTION
**Pull request by CAMOBAP**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Ping @CAMOBAP

**Comment by CAMOBAP** [comment]
I still have a troubles with bundler lookup for `ruby-jing`, `Unable to satisfy the following requirements: (Bundler::Molinillo::VersionConflict)`

@ronaldtse @opoudjis @w00lf if you have any idea why this may happen, please help

**Comment by ronaldtse** [comment]
@CAMOBAP will it pass without `require 'jing'`?

**Comment by CAMOBAP** [comment]
> will it pass without `require 'jing'`?

@ronaldtse nope, I have tried this as a possible solution, but it doesn't work

**Comment by w00lf** [comment]
> I still have a troubles with bundler lookup for `ruby-jing`, `Unable to satisfy the following requirements: (Bundler::Molinillo::VersionConflict)`
> 
> @ronaldtse @opoudjis @w00lf if you have any idea why this may happen, please help

We can try to use build script from ocra docs:
```
ocra someapp/script/rails someapp --output someapp.exe --add-all-core \
--gemfile someapp/Gemfile --no-dep-run --gem-full --chdir-first -- server
```
They supplied this example for complex rails app. If this one does not help me we can try to mention ruby-jing with `--gem-all=ruby-jing` as described here - https://github.com/larsch/ocra/#gem-handling

**Comment by CAMOBAP** [comment]
Looks like it's known issue https://github.com/larsch/ocra/issues/144, if we remove git gem it works

To be honest, I still don't understand why we use a forked version for jing, @ronaldtse @w00lf could you please show some light on https://github.com/metanorma/packed-mn/issues/37

According to my understanding jing gem just a wrapper around `jar` file which embedded in the gem. The gem just call `java -jar ...` for this embedded jar, I didn't see any point why this can/may lead to any issues

**Comment by w00lf** [comment]
> Looks like it's known issue [larsch/ocra#144](https://github.com/larsch/ocra/issues/144), if we remove git gem it works
> 
> To be honest, I still don't understand why we use a forked version for jing, @ronaldtse @w00lf could you please show some light on #37
> 
> According to my understanding jing gem just a wrapper around `jar` file which embedded in the gem. The gem just call `java -jar ...` for this embedded jar, I didn't see any point why this can/may lead to any issues

The issue here was with packed with ruby packer version, because of inmemory fs java can't use this jar file - its exists only in memory, so I hacked it to just skip validation altogether, this what this fork is doing) For ocra gem I think we can use the original gem version, the only downside here is java dependecy.

**Comment by ronaldtse** [comment]
According to @repu1sion :

> seems like you use some custom version of ruby-jing from https://github.com/metanorma/ruby-jing.git
and it doesn't fit because for windows you need ruby-jing x64-mingw32
> and the one you use is not compatible:
> Bundler could not find compatible versions for gem "ruby-jing": (Bundler::VersionConflict)

**Comment by ronaldtse** [comment]
@w00lf regarding Java dependency, we have to copy out the JAR file into system TEMPDIR for system Java to access it. mn2pdf and plantuml are also Java files, we need to ensure they work (maybe in separate issue).

**Comment by CAMOBAP** [comment]
@ronaldtse @w00lf I have an idea to make it work, we can catch `Kernel.system calls` and check jar which used there and unpack them on the fly (similarly as we did with libffi)

**Comment by ronaldtse** [comment]
@CAMOBAP let's do that -- thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP tests still seem to be failing?

**Comment by repu1sion** [comment]
yep, ruby-jing itself is mostly jar, which was not updated from 2014. this could be really an ocra bug which is not able to detect platform correctly, so if one single commit you did in fork was only useful for ruby packer it could be fixed by skipping to original ruby-jing 0.0.1 gem. But I see you already made a workaround.

**Comment by repu1sion** [comment]
about the last fail:
``
C:/Users/RUNNER~1/AppData/Local/Temp/ocr70FD.tmp/src/metanorma:122:in `require': cannot load such file -- metanorma-mpfd (LoadError)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr70FD.tmp/src/metanorma:122:in `<main>'
The system cannot find the path specified.
``

metanorma-mpfd seems to be missed in Gemfile.lock in root of tests repo. Could it be the issue?

**Comment by CAMOBAP** [comment]
> tests still seem to be failing?

@ronaldtse, unfortunately, yes, I'm using CI because on my machine for some reason compilation really slow(

I still working on a workaround for jing, currently, I'm working on the problem with `rng` files which referred from schema

**Comment by CAMOBAP** [comment]
jing fixed, but some new problem appears

1. Known issue
```
Error: File to import not found or unreadable: base_style/all.
        on line 29:1 of stdin
>> @import 'base_style/all';
```

2.
```
asciimath-2.0.0/lib/asciimath/parser.rb:669:in `block in convert_to_matrix': undefined method `each' for #<AsciiMath::AST::Number:0x0000010d604768> (NoMethodError)
```

3.
```
relaton-bib-1.1.1/lib/relaton_bib/bibliographic_item.rb:340:in `to_hash': undefined method `presence?' for #<RelatonItu::StructuredIdentifier:0x00007fbcc61f6fc8> (NoMethodError)
```

Investigation will be continued

**Comment by ronaldtse** [comment]
Problem 2. is fixed in https://github.com/asciidoctor/asciimath/pull/49

**Comment by CAMOBAP** [comment]
http://enclose.io/rubyc/rubyc-linux-x64.gz - broken, I will check later

**Comment by repu1sion** [comment]
I found a funny bug with ocra produced binaries, which leads to errors like:
`require': cannot load such file -- metanorma-rsd (LoadError)`

When we run metanorma.exe binary created by ocra from the directory with some Gemfile - it does Gemfile parsing and relies on it even so in my understanding produced binary should work independently from all other files because its just a single container. 

So when during iso tests we switch in Makefile to dir build/iso for example with Gemfile which doesn't contain references like
```
gem 'metanorma-mpfd'
gem 'metanorma-rsd'
```
we have metanorma-rsd or metanorma-mpfd Load error:

```
c:\archive\develop\packed-mn-orig\build\iso>metanorma.exe -x xml "sources/amendment/rice-amd.np.adoc"
Traceback (most recent call last):
        1: from c:/archive/develop/packed-mn-orig/build/iso/ocr2F02.tmp/src/metanorma:136:in `<main>'
c:/archive/develop/packed-mn-orig/build/iso/ocr2F02.tmp/src/metanorma:136:in `require': cannot load such file -- metanorma-rsd (LoadError)
```
But if we have Gemfile with ref to metanorma-rsd or no Gemfile at all - it works fine and .xml is created:
```
c:\archive\develop\packed-mn-orig> build\metanorma.exe -x xml "build/iso/sources/amendment/rice-amd.np.adoc"
Style: Prefatory material must be followed by (clause) Scope
Style: Normative References must be followed by Terms and Definitions
Style: Document must contain at least one clause
Style: (XML Line 000072): Foreword may contain requirement: ISO shall not be held responsible for identifying any or all such patent rights
Style: (XML Line 000072): Foreword may contain permission: Attention is drawn to the possibility that some of the elements of this document
may be the subject of patent rights
Style: (XML Line 000072): Foreword may contain recommendation: In particular the different approval criteria needed for the different types
of ISO documents should be noted
Style: (XML Line 000114): possible decimal point: 2.1
Syntax: (XML Line 000064:7): element "ics" incomplete; missing required element "text"
Syntax: (XML Line 000066:60): value of attribute "origyr" is invalid; must be an integer
```
I think this is strange and wrong behavior from ocra executables but probably we would need to rework some `cd` in Windows makefiles to get correct tests results.

**Comment by CAMOBAP** [comment]
- https://github.com/relaton/relaton-iho/commit/4e25c561130f9c4d1b1c564edcfb579900a7696a - fixed
 - https://github.com/metanorma/mn-samples-cc/pull/28

Still investigating:

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr1803.tmp/lib/ruby/2.6.0/openssl.rb:13:in `require': 126: The specified module could not be found.   - C:/Users/RUNNER~1/AppData/Local/Temp/ocr1803.tmp/lib/ruby/2.6.0/x64-mingw32/openssl.so (LoadError)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1803.tmp/lib/ruby/2.6.0/openssl.rb:13:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1803.tmp/src/metanorma:6:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr1803.tmp/src/metanorma:6:in `<main>'
```

**Comment by ronaldtse** [comment]
Thanks @CAMOBAP ! Time to tag a release according to the version of metanorma-cli!

**Comment by CAMOBAP** [comment]
@ronaldtse done
