### PR TITLE
Make macOS/Linux metanorma executable work with isodoc 1.0.23+

### PR DESCRIPTION
**Pull request by w00lf**
#23 

Updated all metanorma flavors gems to the latest versions, fixed compilation errors, for scss include issue i created a patch in scss fork: https://github.com/metanorma/sassc-ruby/commit/ce6c3a65b29247476ea1cf1c0f53cf7d5fe46827. After the update there is an issue with `iso-639` gem: for some reason, language file that they use is not read properly inside the compiled application, i was forced to downgrade gem version to 0.2.10.

### CODE REVIEW

**Comment by ronaldtse** [comment]
@w00lf is it possible to clean up the Gemfile completely to only contain:

* metanorma-cli (which will require the rest)
* sassc-ruby
* ruby-king

?

**Comment by CAMOBAP795** [comment]
LGTM, @w00lf to be on the same path, is this all changeset to fix the issue which was discovered in https://github.com/metanorma/packed-mn/issues/20#issuecomment-611380025 ?

Or the issue was been fixed in other repos too?

**Comment by w00lf** [comment]
> @w00lf is it possible to clean up the Gemfile completely (and remove Gemfile.lock) to only contain:
> 
> * metanorma-cli (which will require the rest)
> * sassc-ruby
> * ruby-king
> 
> ?
> 
> Then we can build any version we want, technically.

Yes i thnk its possible, i will create an issue for this.

**Comment by w00lf** [comment]
> #20 (comment)

Yes, this PR fixes all issues in #20

**Comment by ronaldtse** [comment]
Thanks @w00lf !
